.github/workflows/be-dev-ci.yml
.github/workflows/be-release-cd.yml
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/BeMyCarMasterApplication.java

- #42 
- cd workflow 설정
- docker image build
- docker hub push
- deploy to AWS

[Setting] cd workflow 설정

---

.github/workflows/be-release-cd.yml

[Release] cd workflow typo 수정

---

.github/workflows/be-release-cd.yml

- #42 
- codedeploy 실행을 위한 appspec.yml 추가
- cd workflow 의 root 경로 설정

[Setting] appspec 추가

---

.github/workflows/be-release-cd.yml

- appspec.yml 추가
- 작업간 root 경로 설정

[Release] appspec 추가

---

.github/workflows/be-release-cd.yml

- #42 
- s3로 Zip  파일 복사전 작업 경로 수정

[Chore] cd workflow의 작업 경로 수정

---

.github/workflows/be-release-cd.yml

[Release] cd workflow의 작업 경로 수정

---

.github/workflows/be-dev-ci.yml
.github/workflows/be-release-cd.yml
BE-MyCarMaster/.gitignore
BE-MyCarMaster/build.gradle
BE-MyCarMaster/src/main/resources/application-api.yml
BE-MyCarMaster/src/main/resources/application-domain.yml

- #42 
- 기존에는 submodule로 env 파일 관리. <br/>
- 보안 이슈로 secrets를 사용해 env 파일 관리 하는 방식으로 변경

[Setting] Github Secrets로 env 파일 관리

---

.github/workflows/be-dev-ci.yml
.github/workflows/be-release-cd.yml
BE-MyCarMaster/.gitignore
BE-MyCarMaster/build.gradle
BE-MyCarMaster/src/main/resources/application-api.yml
BE-MyCarMaster/src/main/resources/application-domain.yml

- 기존에 submodule을 사용하던 방식에서 secrets로 관리하는 방식으로 변경

[Release] ENV 파일 관리 방식 변경

---

.github/workflows/be-release-cd.yml
BE-MyCarMaster/Dockerfile
BE-MyCarMaster/src/main/resources/application-domain.yml

[Release] Dockerfile에서 Env값 관리

---

FE-MyCarMaster/src/components/Main/MainView.tsx
FE-MyCarMaster/src/components/common/CategoryList/CategoryItem.tsx
FE-MyCarMaster/src/components/common/NavigationList/EstimatedPrice.tsx
FE-MyCarMaster/src/components/common/NavigationList/NavigationItem.tsx
FE-MyCarMaster/src/components/common/NavigationList/NavigationList.tsx

- #33
- 네비게이션 컴포넌트 생성
- 옵션을 선택하면 자연스럽게 네비게이션 리스트의 height가 늘어나야하는데, 리렌더링으로 해결해야한다!

[Feature] 재사용 컴포넌트 생성 - 2

---

BE-MyCarMaster/appspec.yml

[Release] appspec 내용 추가후 배포

---

FE-MyCarMaster/src/pages/Home.tsx

- #6
- video tag 내 min-height: 100% -> 100vh

[Design] 홈 화면 레이아웃 구성

---

FE-MyCarMaster/src/components/Footer/Footer.tsx
FE-MyCarMaster/vercel.json

[Setting] 프론트엔드 Vercel 배포

---

BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/engine/controller/EngineController.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/engine/dto/request/GetEnginesRequest.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/engine/dto/response/Engine.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/engine/dto/response/GetEnginesResponse.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/engine/usecase/GetEnginesUseCase.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/model/controller/ModelController.java

- #9 
- 엔진 목록 조회 swagger 문서 생성을 위해 관련 클래스 구현

[Feat] 엔진 목록 조회 swagger 문서 작성

---

BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/controller/ColorController.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/dto/request/GetExteriorColorsRequest.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/dto/response/ExteriorColor.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/dto/response/GetExteriorColorsResponse.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/dto/response/InteriorColor.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/usecase/GetExteriorColorsUseCase.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/usecase/GetInteriorColorsUseCase.java

- #22 
- 외장 색상 목록 조회 swagger 문서 생성을 위해 관련 클래스 구현

[Feature] 외장 색상 목록 조회 swagger 문서 작성

---

FE-MyCarMaster/README.md
FE-MyCarMaster/src/pages/Home.tsx

- #78 
- ignore build step 변경(실패)
구글링을 통해 찾아보았을 때 ignore build step을 통해 해당 브랜치에 push되었을 때 deploy되게 가능하다고 하였는데, 해보았는데 안된다..
무엇이 해결방안인가..

[Setting] 프론트 Vercel 배포 테스트

---

FE-MyCarMaster/src/components/Footer/Footer.tsx
FE-MyCarMaster/src/components/Header/Header.tsx
FE-MyCarMaster/src/components/common/Button/Button.tsx
FE-MyCarMaster/src/pages/Home.tsx

- #5 
- Footer 레이아웃 구성
- Footer 우하단 이전,다음 버튼 추가

[Feature] Footer 레이아웃을 구성한다.

---

FE-MyCarMaster/src/App.tsx
FE-MyCarMaster/src/components/Header/Header.tsx
FE-MyCarMaster/src/contexts/CarPaintContext.tsx
FE-MyCarMaster/src/contexts/DetailContext.tsx
FE-MyCarMaster/src/contexts/ModelContext.tsx
FE-MyCarMaster/src/contexts/OptionContext.tsx
FE-MyCarMaster/src/contexts/QuotationContext.tsx
FE-MyCarMaster/src/contexts/TrimContext.tsx

- #104
- ModelContext, TrimContext 구현
- AppProvider로 Providers 제어
- Header의 modelName 적용 확인
- `++(8/5)` DetailProvider, CarPaintProvider, OptionProvider, QuotationProvider 구현 및 제어
```jsx
import { useReducer, createContext, useContext } from "react";
type ModelState = {
modelId: number;
modelName: string;
};
type ModelAction = {
type: "SET_MODEL";
payload: { modelId: number; modelName: string };
};
const initialModelState: ModelState = {
modelId: 0,
modelName: "Palisade",
};
type ModelDispatch = (action: ModelAction) => void;
const modelReducer = (state: ModelState, action: ModelAction): ModelState => {
switch (action.type) {
case "SET_MODEL":
return {
...state,
modelId: action.payload.modelId,
modelName: action.payload.modelName,
};
default:
return state;
}
};
const ModelStateContext = …
```

[Feature] Context Provider 구성

---

.github/workflows/be-release-cd.yml
BE-MyCarMaster/appspec.yml
BE-MyCarMaster/scripts/appspec.yml
BE-MyCarMaster/scripts/create-directory.sh
BE-MyCarMaster/scripts/pull-and-run-container.sh
BE-MyCarMaster/scripts/remove-container.sh

- #42 
- 배포 유형 변경에 따라 Script 추가
- be-release-cd.yml 내용 수정

[Feature] 배포유형 변경에 따른 Script 추가

---

BE-MyCarMaster/scripts/appspec.yml

- #42 
- script location에 잘못된 path 제거
- files section 제거

[Chore] appspec의 script location 수정

---

BE-MyCarMaster/scripts/appspec.yml

[Release] 배포 스크립트의 location 수정

---

BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/interior/controller/InteriorColorController.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/interior/dto/request/GetInteriorColorsRequest.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/interior/dto/response/GetInteriorColorsResponse.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/interior/dto/response/InteriorColorDto.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/interior/usecase/GetInteriorColorsUseCase.java
BE-MyCarMaster/src/test/java/softeer/bemycarmaster/api/domain/color/exterior/controller/ExteriorColorControllerTest.java
BE-MyCarMaster/src/test/java/softeer/bemycarmaster/api/domain/color/interior/controller/InteriorColorControllerTest.java

- #23 
- 내장 색상 예외 처리 추가
- 내장 색상 TC 작성

[Feature] 내장 색상 예외 처리 로직 추가

---

BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/bodytype/controller/BodyTypeController.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/bodytype/dto/request/GetBodyTypesRequest.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/bodytype/dto/response/BodyTypeDto.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/bodytype/dto/response/GetBodyTypesResponse.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/bodytype/usecase/GetBodyTypesUseCase.java
BE-MyCarMaster/src/test/java/softeer/bemycarmaster/api/domain/bodytype/controller/BodyTypeControllerTest.java

- #19 
- 바디타입 목록 조회 예외 처리 로직 추가
- 바디타입 목록 조회 TC 작성
- BodyType -> BodyTypeDto rename

[Feature] 바디타입 목록 조회 예외 처리 로직 추가

---

BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/model/domain/Model.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/model/dto/response/GetModelsResponse.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/model/dto/response/ModelDto.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/model/infrastructure/ModelEntity.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/model/infrastructure/ModelJpaAdaptor.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/model/infrastructure/ModelJpaRepository.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/model/usecase/GetModelsUseCase.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/model/usecase/port/ModelPort.java
BE-MyCarMaster/src/test/java/softeer/bemycarmaster/api/domain/model/controller/ModelControllerTest.java
BE-MyCarMaster/src/test/java/softeer/bemycarmaster/api/domain/model/usecase/GetModelsUseCaseTest.java

- #2 
- UseCase 구현
- Port & Adaptor로 비즈니스 로직으로부터 JPA 의존성 디커플링
- UseCase TC 작성

[Feature] 모델 목록 조회 구현

---

FE-MyCarMaster/src/components/Footer/Footer.tsx
FE-MyCarMaster/src/components/Main/MainView.tsx
FE-MyCarMaster/src/components/Main/MainWrapper.tsx
FE-MyCarMaster/src/contexts/QuotationContext.tsx

- #5
- 우측 하단 Footer 버튼 이벤트 등록
- Quotation 액션 등록 및 적용 확인
```jsx
// action - QutotationContext.tsx
type QuotationAction =
| {
type: "NAVIGATE";
payload: { navigationId: number; isFirst?: boolean[] };
}
// usage - Footer.tsx
function Footer() {
const { navigationId } = useQuotationState();
const quotationDispatch = useQuotationDispatch();
const prevButtonHandler = () => {
quotationDispatch({
type: "NAVIGATE",
payload: {
navigationId: navigationId - 1,
},
});
};
...
}
```

[Feature] 견적 요약 네비게이션 생성

---

BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/bodytype/controller/BodyTypeController.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/wheeldrive/controller/WheelDriveController.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/wheeldrive/dto/request/GetWheelDrivesRequest.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/wheeldrive/dto/response/GetWheelDrivesResponse.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/wheeldrive/dto/response/WheelDriveDto.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/wheeldrive/usecase/GetWheelDrivesUseCase.java
BE-MyCarMaster/src/test/java/softeer/bemycarmaster/api/domain/wheeldrive/controller/WheelDriveControllerTest.java

- #21 
- 구동방식 목록 조회 예외 처리 로직 추가
- 구동방식 목록 조회 TC 작성
- WheelDrive -> WheelDriveDto rename

[Feature] 구동방식 목록 조회 예외 처리 로직 추가

---

BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/engine/controller/EngineController.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/engine/dto/request/GetEnginesRequest.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/engine/dto/response/EngineDto.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/engine/dto/response/GetEnginesResponse.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/engine/usecase/GetEnginesUseCase.java
BE-MyCarMaster/src/test/java/softeer/bemycarmaster/api/domain/engine/controller/EngineControllerTest.java

- #9 
엔진 목록 조회 예외 처리 로직 추가
엔진 목록 조회 TC 작성
Engine -> EngineDto rename

[Feature] 엔진 목록 조회 예외 처리 로직 추가

---

BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/trim/controller/TrimController.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/trim/dto/request/GetTrimsRequest.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/trim/dto/response/GetTrimsResponse.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/trim/dto/response/Trim.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/trim/dto/response/TrimDto.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/trim/usecase/GetTrimsUseCase.java
BE-MyCarMaster/src/test/java/softeer/bemycarmaster/api/domain/trim/controller/TrimControllerTest.java

- #3 
- 트림 목록 조회 예외 처리 로직 추가
- 트림 목록 조회 TC 작성
- Trim -> TrimDto로 rename

[Feature] 트림 목록 조회 예외 처리 로직 추가

---

FE-MyCarMaster/src/components/Main/view/DetailModelView/EngineView.tsx
FE-MyCarMaster/src/components/common/CategoryList/CategoryItem.tsx
FE-MyCarMaster/src/components/common/CategoryList/CategoryList.tsx
FE-MyCarMaster/src/components/common/Graph/GraphItem.tsx
FE-MyCarMaster/src/components/common/Graph/GraphList.tsx
FE-MyCarMaster/src/components/common/Graph/ProgressBar.tsx
FE-MyCarMaster/src/constants/Graph.constants.ts

- #10 
- 엔진의 성능을 확인할 수 있도록 그래프 리스트와 그래프 아이템를 구현
- 출력, 토크, 연비에 프로그래스 바를 추가하여 엔진마다 성능의 차이를 직관적으로 확인할 수 있도록 함
- 숫자도 프로그래스 형태로 0부터 시작하여 올라가게 할까? -> 우선 메인 기능 전체 구현되면 추가하기로!

[Feature] 엔진 뷰를 구성하고 최고출력, 최대토크, 복합 연비 프로그래스 바를 구성한다.

---

BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/model/controller/ModelController.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/model/domain/Model.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/model/infrastructure/ModelEntity.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/model/infrastructure/ModelJpaAdaptor.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/model/usecase/port/ModelPort.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/trim/controller/TrimController.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/trim/domain/Trim.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/trim/dto/request/GetTrimsRequest.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/trim/dto/response/GetTrimsResponse.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/trim/dto/response/TrimDto.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/trim/infrastructure/TrimEntity.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/trim/infrastructure/TrimJpaAdaptor.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/trim/infrastructure/TrimJpaRepository.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/trim/usecase/GetTrimsUseCase.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/trim/usecase/port/TrimPort.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/global/annotation/Adaptor.java
BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/global/annotation/Port.java
BE-MyCarMaster/src/test/java/softeer/bemycarmaster/api/domain/trim/usecase/GetTrimsUseCaseTest.java

- #3 
- 트림 목록 조회 구현
- 식별값 Integer -> Long으로 변경

[Feature] 트림 목록 조회 구현 

---

FE-MyCarMaster/src/components/Footer/view/ColorSelect.tsx
FE-MyCarMaster/src/components/Footer/view/ColorView/ExteriorColorSelectView.tsx
FE-MyCarMaster/src/components/Footer/view/ColorView/InteriorColorSelectView.tsx
FE-MyCarMaster/src/components/Footer/view/DetailModelSelect.tsx
FE-MyCarMaster/src/components/Footer/view/DetailModelView/BodyTypeSelectView.tsx
FE-MyCarMaster/src/components/Footer/view/DetailModelView/EngineSelectView.tsx
FE-MyCarMaster/src/components/Footer/view/DetailModelView/WheelDriveSelectView.tsx
FE-MyCarMaster/src/components/Footer/view/OptionSelect.tsx
FE-MyCarMaster/src/components/Footer/view/TrimSelect.tsx
FE-MyCarMaster/src/components/Main/view/ColorView/ColorWrapper.tsx
FE-MyCarMaster/src/components/Main/view/ColorView/ExteriorColorView.tsx
FE-MyCarMaster/src/components/Main/view/ColorView/InteriorColorView.tsx
FE-MyCarMaster/src/components/common/ColorBox/InnerColorBox.tsx
FE-MyCarMaster/src/components/common/ColorBox/OuterColorBox.tsx
FE-MyCarMaster/src/contexts/CarPaintContext.tsx
FE-MyCarMaster/src/contexts/QuotationContext.tsx
FE-MyCarMaster/src/pages/Home.tsx

- #13 
- #14
- 외/내장 색상 동적으로 뷰를 제어할 수 있다.
- DetailModelSelect, ColorSelect 분리

[Feature] 외/내장 색상 뷰 구성

---

iOS-MyCarMaster/MCMResource/MCMResource.xcodeproj/project.pbxproj
iOS-MyCarMaster/MCMResource/MCMResource/Generated/Font+Generated.swift
iOS-MyCarMaster/MCMResource/MCMResource/Resource.swift
iOS-MyCarMaster/MCMResource/MCMResource/String+TextStyle.swift
iOS-MyCarMaster/MCMResource/MCMResource/TextStyle.swift
iOS-MyCarMaster/MCMResource/MCMResource/UIKit+Extension/UIButton+Extension.swift
iOS-MyCarMaster/MCMResource/MCMResource/UIKit+Extension/UILabel+TextStyle.swift
iOS-MyCarMaster/MCMResource/README.md

- #142 
- 서체 스타일 관리 시스템 구현
- Figma에 정의된 서체를 선언적으로 관리
- docs 작성
- 없음

[Feature] 서체 스타일 관리 시스템 구현

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/engine/dto/response/EngineDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/engine/dto/response/GetEnginesResponse.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/engine/usecase/GetEnginesUseCase.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/engine/usecase/port/EnginePort.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/body_type/BodyType.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/engine/Engine.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/body_type/adaptor/BodyTypeJpaAdaptor.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/body_type/entity/BodyTypeEntity.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/body_type/repository/BodyTypeJpaRepository.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/engine/adpator/EngineJpaAdaptor.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/engine/entity/EngineEntity.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/engine/entity/TrimEngineEntity.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/engine/repository/TrimEngineJpaRepository.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/engine/usecase/GetEnginesUseCaseTest.java

- #9 
- bodyType 패키지 구조 수정
- 엔진 목록 조회 구현

[Feature] 엔진 목록 조회 구현

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/wheeldrive/controller/WheelDriveController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/wheeldrive/dto/request/GetWheelDrivesRequest.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/wheeldrive/dto/response/GetWheelDrivesResponse.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/wheeldrive/dto/response/WheelDriveDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/wheeldrive/usecase/GetWheelDrivesUseCase.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/wheeldrive/usecase/port/WheelDrivePort.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/wheel_dirve/WheelDrive.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/wheel_drive/adaptor/WheelDriveJpaAdaptor.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/wheel_drive/entity/TrimWheelDriveEntity.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/wheel_drive/entity/UnselectableEngineWheelDriveEntity.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/wheel_drive/entity/WheelDriveEntity.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/wheel_drive/repository/TrimWheelDriveJpaRepository.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/wheel_drive/repository/UnselectableEngineWheelDriveJpaRepository.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/wheeldrive/controller/WheelDriveControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/wheeldrive/usecase/GetWheelDrivesUseCaseTest.java

- #21 
- 구동방식 목록 조회 API Spec 수정 (trimId, engineId로 선택가능한 구동방식 조회하도록)
- 트림, 엔진에 따라 선택가능한 구동방식 목록 조회 기능 구현

[Feature] 구동방식 목록 조회 구현

---

FE-MyCarMaster/src/assets/icons/CirclePagination.svg
FE-MyCarMaster/src/components/Footer/view/OptionSelect.tsx
FE-MyCarMaster/src/components/Main/view/OptionContent.tsx
FE-MyCarMaster/src/components/common/ColorBox/InnerColorBox.tsx
FE-MyCarMaster/src/components/common/ColorBox/OuterColorBox.tsx
FE-MyCarMaster/src/components/common/OptionBox/OptionBox.tsx
FE-MyCarMaster/src/components/common/OptionDescription/OptionDescription.tsx
FE-MyCarMaster/src/contexts/OptionContext.tsx
FE-MyCarMaster/src/types/options.types.ts

- #15 
- optionContext에 optionId를 추가하여 메인 컨텐츠 변경

[Feature] 옵션 Footer Item에 따른 메인 컨텐츠 변경

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/color_exterior/entity/TrimExteriorColorEntity.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/color_interior/entity/TrimInteriorColorEntity.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/color_interior/entity/UnselectableExteriorInteriorEntity.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/engine/entity/TrimEngineEntity.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/wheel_drive/entity/TrimWheelDriveEntity.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/wheel_drive/entity/UnselectableEngineWheelDriveEntity.java

- Entity에서 테이블명을 설정해주지 않아, '_entity'가 붙는 경우가 발생.
- 이런 경우를 없애기 위해 @Table을 통해 테이블명 명시

[Setting] 테이블명 설정

---

BE-MyCarMaster/src/main/resources/application-domain.yml

- 데이터 삽입 완료
- 데이터 보존을 위한 ddl-auto none 설정

[Setting] ddl-auto 설정

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/trim/controller/TrimController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/exception/BindingParamException.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/exception/GlobalExceptionHandler.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/trim/controller/TrimControllerTest.java

- #트림 목록
- FE 개발 환경상 GET 요청에 body 담아주지 못하는 상황
- 이에 따라 body에 json으로 요청받는 형식에서 query param으로 받는 형식으로 변경

[Fix] 트림 목록 조회 요청 형식 변경

---

FE-MyCarMaster/.gitignore
FE-MyCarMaster/src/components/Main/view/TrimContent.tsx
FE-MyCarMaster/src/contexts/TrimContext.tsx
FE-MyCarMaster/src/hooks/useFetch.ts

- #153 
- useFetch custom hook 구현

[Feature] useFetch API custom hook 구현

---

FE-MyCarMaster/src/components/Footer/view/DetailModelView/BodyTypeSelectView.tsx
FE-MyCarMaster/src/components/Footer/view/DetailModelView/EngineSelectView.tsx
FE-MyCarMaster/src/components/Footer/view/DetailModelView/WheelDriveSelectView.tsx
FE-MyCarMaster/src/components/Footer/view/OptionSelect.tsx
FE-MyCarMaster/src/components/common/NavigationList/NavigationItem.tsx
FE-MyCarMaster/src/components/common/OptionBox/OptionBox.tsx
FE-MyCarMaster/src/components/common/OptionBox/OptionBoxName.tsx
FE-MyCarMaster/src/components/common/OptionBox/OptionBoxTopPrice.tsx
FE-MyCarMaster/src/components/common/OptionBox/style.ts
FE-MyCarMaster/src/contexts/OptionContext.tsx
FE-MyCarMaster/src/contexts/QuotationContext.tsx
FE-MyCarMaster/src/styles/GlobalStyle.ts
FE-MyCarMaster/src/styles/Theme.ts
FE-MyCarMaster/src/types/quotation.types.ts

[Design] 옵션박스 컴포넌트 디자인

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/engine/controller/EngineController.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/engine/controller/EngineControllerTest.java

- #9 
- json body -> query param으로 변경

[Fix] 엔진 목록 조회 요청 형식 query param으로 변경

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/wheeldrive/controller/WheelDriveController.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/wheeldrive/controller/WheelDriveControllerTest.java

- #21 
- json body -> query param으로 변경

[Fix] 구동방식 목록 조회 요청 형식 query param으로 변경

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/body_type/controller/BodyTypeController.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/body_type/controller/BodyTypeControllerTest.java

- #19 
- json body -> query param으로 변경

[Fix] 바디타입 목록 조회 요청 형식 query param으로 변경

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/controller/OptionController.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/option/controller/OptionControllerTest.java

- #24 
- body에 json으로 요청하는 형식에서 query param으로 변경

[Fix] 추가 옵션 목록 조회 요청 형식 query param으로 변경

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/color_exterior/controller/ExteriorColorController.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/color_exterior/controller/ExteriorColorControllerTest.java

- #22 
- body에 json으로 요청하는 형식에서 query param으로 변경

[Fix] 외장 목록 조회 요청 형식 query param으로 변경

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/color_interior/controller/InteriorColorController.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/color_interior/controller/InteriorColorControllerTest.java

- #23 
- body에 json으로 요청하는 형식에서 query param으로 변경

[Fix] 내장 목록 조회 요청 형식 query param으로 변경

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/engine/controller/EngineController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/engine/dto/request/GetUnselectableOptionsByEngineRequest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/engine/controller/EngineControllerTest.java

- #17
- json body -> query param으로 변경

[Fix] 엔진에 따라 선택불가능해지는 옵션 목록 조회 요청 형식 query param으로 변경 

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/body_type/controller/BodyTypeController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/color_exterior/controller/ExteriorColorController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/color_interior/controller/InteriorColorController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/engine/controller/EngineController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/engine/dto/request/GetUnselectableOptionsByEngineRequest.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/controller/OptionController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/trim/controller/TrimController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/wheeldrive/controller/WheelDriveController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/exception/BindingParamException.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/exception/GlobalExceptionHandler.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/engine/entity/EngineEntity.java
BE-MyCarMaster/src/main/resources/application-domain.yml
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/body_type/controller/BodyTypeControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/color_exterior/controller/ExteriorColorControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/color_interior/controller/InteriorColorControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/engine/controller/EngineControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/option/controller/OptionControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/trim/controller/TrimControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/wheeldrive/controller/WheelDriveControllerTest.java

- 요청 형식 body json -> query param 으로 변경

[Release] 요청 형식 변경

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/body_type/controller/BodyTypeController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/color_exterior/controller/ExteriorColorController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/color_interior/controller/InteriorColorController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/engine/controller/EngineController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/controller/OptionController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/trim/controller/TrimController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/wheeldrive/controller/WheelDriveController.java

- 스웨거 문서의 request parameter 포맷을 쿼리로 수정하기 위해 컨트롤러의 request에 @ParameterObject 어노테이션 추가
- 스웨거 테스트 에러도 고쳐졌다--!
- fix가 맞나...?

[Docs] swagger request param 포맷 쿼리로 수정 및 테스트 에러 해결

---

FE-MyCarMaster/src/components/Footer/view/ColorView/ExteriorColorSelectView.tsx
FE-MyCarMaster/src/components/Footer/view/DetailModelView/BodyTypeSelectView.tsx
FE-MyCarMaster/src/components/Footer/view/DetailModelView/EngineSelectView.tsx
FE-MyCarMaster/src/components/Footer/view/DetailModelView/WheelDriveSelectView.tsx
FE-MyCarMaster/src/components/Footer/view/TrimSelect.tsx
FE-MyCarMaster/src/components/Main/view/ColorView/ExteriorColorView.tsx
FE-MyCarMaster/src/components/Main/view/DetailModelView/BodyTypeView.tsx
FE-MyCarMaster/src/components/Main/view/DetailModelView/EngineView.tsx
FE-MyCarMaster/src/components/Main/view/DetailModelView/WheelDriveView.tsx
FE-MyCarMaster/src/components/Main/view/TrimContent.tsx
FE-MyCarMaster/src/components/common/CategoryList/CategoryList.tsx
FE-MyCarMaster/src/components/common/Graph/GraphList.tsx
FE-MyCarMaster/src/contexts/CarPaintContext.tsx
FE-MyCarMaster/src/contexts/DetailContext.tsx
FE-MyCarMaster/src/contexts/ModelContext.tsx
FE-MyCarMaster/src/contexts/OptionContext.tsx
FE-MyCarMaster/src/contexts/TrimContext.tsx

- #171 
- 트림, 세부모델, 색상 조회 API 연동

[Feature] 트림, 세부 모델, 색상 조회 API 연동

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/HealthController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/config/cors/CorsConfig.java

- #42 
- vercel 기본 도메인에서 my-car-master.shop 으로 변경

[Setting] CORS 설정 수정

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/HealthController.java

[Fix] checkStyle 수정

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/HealthController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/body_type/controller/BodyTypeController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/color_exterior/controller/ExteriorColorController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/color_interior/controller/InteriorColorController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/engine/controller/EngineController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/controller/OptionController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/trim/controller/TrimController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/wheeldrive/controller/WheelDriveController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/config/cors/CorsConfig.java

- #42 
- vercel 기본 도메인에서 my-car-master.shop 으로 변경

[Release] CORS 설정 수정

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/dto/response/OptionDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/dto/response/SubOptionDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/option/Option.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/adaptor/OptionJpaAdaptor.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/entity/OptionEntity.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/entity/TrimAdditionalOptionEntity.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/repository/TrimAdditionalOptionJpaRepository.java
BE-MyCarMaster/src/main/resources/application-domain.yml

- #24 
- 지연 로딩을 위한 @Transactional 설정
- batch size 설정
- OptionEntity와 SuperSubEntity 간의 관계를 명확하게 코드 수준에서 이해 필요

[Fix] 추가 옵션 목록 조회 로직 수정

---

FE-MyCarMaster/src/components/Footer/view/ColorView/ExteriorColorSelectView.tsx
FE-MyCarMaster/src/components/Footer/view/ColorView/InteriorColorSelectView.tsx
FE-MyCarMaster/src/components/Footer/view/DetailModelView/BodyTypeSelectView.tsx
FE-MyCarMaster/src/components/Footer/view/DetailModelView/EngineSelectView.tsx
FE-MyCarMaster/src/components/Footer/view/DetailModelView/WheelDriveSelectView.tsx
FE-MyCarMaster/src/components/Footer/view/TrimSelect.tsx
FE-MyCarMaster/src/components/Main/view/ColorView/ExteriorColorView.tsx
FE-MyCarMaster/src/components/Main/view/ColorView/InteriorColorView.tsx
FE-MyCarMaster/src/components/Main/view/DetailModelView/BodyTypeView.tsx
FE-MyCarMaster/src/components/Main/view/DetailModelView/EngineView.tsx
FE-MyCarMaster/src/components/Main/view/DetailModelView/WheelDriveView.tsx
FE-MyCarMaster/src/components/Main/view/TrimContent.tsx
FE-MyCarMaster/src/components/common/ColorBox/OuterColorBox.tsx
FE-MyCarMaster/src/components/common/Graph/GraphList.tsx

[Fix] 전역 데이터 동작 에러 처리

---

FE-MyCarMaster/src/components/Main/view/ColorView/ExteriorColorView.tsx
FE-MyCarMaster/src/components/common/CarRotation/CarRotation.tsx

- #194 
- 외부색상과 견적서 완성 페이지(Quotation Page)에 사용될 차량 360도 회전 컴포넌트 구현하였습니다.

[Feature] 차량 360도 회전 컴포넌트 구현

---

iOS-MyCarMaster/MCMNetwork/MCMNetwork/Resources/Dependency.swift
iOS-MyCarMaster/MyCarMaster/MyCarMaster.xcodeproj/project.pbxproj
iOS-MyCarMaster/MyCarMaster/MyCarMaster/Model/DataTransferObject/Dummy/TrimDTODummy.json
iOS-MyCarMaster/MyCarMaster/MyCarMaster/Model/DataTransferObject/RootDTO.swift
iOS-MyCarMaster/MyCarMaster/MyCarMaster/Model/DataTransferObject/TrimDTO.swift
iOS-MyCarMaster/MyCarMaster/MyCarMaster/Model/Entity/Trim.swift
iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Trim/TrimView.swift
iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Trim/TrimViewController.swift

- #29
- 모든 API의 Response를 나타내는 구조체인 RootDTO구현
- RootDTO의 result값에서 API에 따라 바뀐 key에 따라 Decoding하는 로직 구현
- Trim API를 통해 받아온 TrimDTO를 변환하여 listView에 보여주는 동작 구현
- API에 따라서 달라지는 key값을 공통적으로 Decoding하기 위한 로직
- <img width="400" alt="image" src="https://github.com/softeerbootcamp-2nd/H5-MyCarMaster/assets/46219689/717911be-9b01-4aad-a77e-6ff943228a95">
- 어려웠다....

[Feature] Trim API 연동

---

iOS-MyCarMaster/MVIFoundation/MVIFoundation.xcodeproj/xcshareddata/xcschemes/MVIFoundation.xcscheme
iOS-MyCarMaster/MyCarMaster/MyCarMaster.xcodeproj/project.pbxproj
iOS-MyCarMaster/MyCarMaster/MyCarMaster/Model/DataTransferObject/RootDTO.swift
iOS-MyCarMaster/MyCarMaster/MyCarMaster/Model/DataTransferObject/WheelDriveDTO.swift
iOS-MyCarMaster/MyCarMaster/MyCarMaster/Model/Entity/WheelDrive.swift
iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/WheelDrive/WheelDriveView.swift
iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/WheelDrive/WheelDriveViewController.swift

- #27 
- WheelDrive Entity, DTO 추가
- WheelDrive API와 연결
- 없음

[Feature] WheelDrive API 연동

---

FE-MyCarMaster/src/components/Footer/Footer.tsx
FE-MyCarMaster/src/components/common/OptionBox/OptionBox.tsx
FE-MyCarMaster/src/components/common/OptionBox/OptionBoxName.tsx
FE-MyCarMaster/src/components/common/OptionBox/style.ts
FE-MyCarMaster/src/components/common/SearchTrimBox/SearchTrimBox.tsx
FE-MyCarMaster/src/components/common/SearchTrimBox/style.ts
FE-MyCarMaster/src/components/common/TagItem/TagItem.tsx
FE-MyCarMaster/src/components/common/TagItem/style.ts
FE-MyCarMaster/src/styles/Theme.ts

- #189 
- OptionBox 컴포넌트 스타일링
- SearchTrimBox 컴포넌트 스타일링
- TagItem 컴포넌트 스타일링
- OptionBox와 SearchTrimBox는 비슷하나, 같은 컴포넌트 내에 작성하기에는 또 분기로 나눠야 되고 예외적인 부분이 많아서.. 별개로 구분하였습니다.

[Feature] 하단 확장에 사용되는 재사용 컴포넌트 생성

---

iOS-MyCarMaster/MyCarMaster/MyCarMaster/General/Cell/BasicListCell.swift
iOS-MyCarMaster/MyCarMaster/MyCarMaster/General/Cell/ColorListCell.swift
iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/BodyType/BodyTypeViewController.swift
iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Engine/EngineViewController.swift
iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Exterior/ExteriorViewController.swift
iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Trim/TrimViewController.swift
iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/WheelDrive/WheelDriveViewController.swift

- #20
- #25 
- #27 
- #29 
- #30 
- Step에 진입시 Preset이 설정되도록 했다.
- 이전 PR에 올렸던, 셀 선택시 `didDeselect`에서 오류가 나던 버그 수정
- 없음

[Feature] Step에 진입시 Preset이 설정됨

---

FE-MyCarMaster/src/components/Footer/Footer.tsx
FE-MyCarMaster/src/components/Main/view/ColorView/ExteriorColorView.tsx
FE-MyCarMaster/src/components/common/CarRotation/CarRotation.tsx
FE-MyCarMaster/src/components/common/CheckBox/style.ts
FE-MyCarMaster/src/components/common/QuotationList/QuotationList.tsx
FE-MyCarMaster/src/components/common/QuotationList/QuotationOptionItem.tsx
FE-MyCarMaster/src/components/common/QuotationList/QuotationOptionList.tsx

[Fix]: lint 경고 수정

---

.github/workflows/fe-build.yml
.github/workflows/fe-deploy.yml

- #16 
- VITE SERVER APP URL 변수 추가하였습니다.

[Release] 프론트엔드 배포 세팅 (최종)

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/color_exterior/dto/response/GetExteriorColorsResponse.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/color_interior/dto/response/GetInteriorColorsResponse.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/color_exterior/controller/ExteriorColorControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/color_exterior/usecase/GetExteriorColorsUseCaseTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/color_interior/controller/InteriorColorControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/color_interior/usecase/GetInteriorColorsUseCaseTest.java

- #133 #23 
- 색상 목록 조회 response에서 외장, 내장 색상 구분

[Chore] 색상 목록 조회 response에서 외장, 내장 색상 구분

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/agency/entity/AgencyEntity.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/car_master/entity/CarMasterEntity.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/store/entity/StoreEntity.java

- #217
- 카마스터, 대리점 데이터 import를 위해 entity 생성

[Feature] car master, store entity 구현

---

BE-MyCarMaster/Dockerfile
BE-MyCarMaster/start-app.sh

- Pinpoint-agent Prod 환경에서만 동작하도록 설정

[Setting] Pinpoint-agent 설정

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/entity/OptionEntity.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/entity/TrimAdditionalOptionEntity.java

- #24 
- 기획 추가분석 및 현차 내차만들기 페이지 분석 결과, 추가 옵션 가격이 트림에 따라 달라지는 것이 아니라 옵션마다 가격이 같다고 판단하여
- 추가비용을 option 테이블로 옮김
- refactor인가..?

[Feature] trim_additional_optoin의 price를 option으로 이동

---

FE-MyCarMaster/src/components/Footer/Footer.tsx
FE-MyCarMaster/src/components/Footer/SelectListWrapper.tsx
FE-MyCarMaster/src/components/Main/view/ColorView/ExteriorColorView.tsx
FE-MyCarMaster/src/components/Main/view/ColorView/InteriorColorView.tsx
FE-MyCarMaster/src/components/common/Button/TextButton.tsx
FE-MyCarMaster/src/components/common/NavigationList/NavigationItem.tsx
FE-MyCarMaster/src/components/common/QuotationList/QuotationItem.tsx
FE-MyCarMaster/src/components/common/QuotationList/QuotationList.tsx
FE-MyCarMaster/src/components/common/QuotationList/QuotationOptionItem.tsx
FE-MyCarMaster/src/components/common/QuotationList/QuotationOptionList.tsx
FE-MyCarMaster/src/components/common/SearchTrimBox/SearchTrimBox.tsx
FE-MyCarMaster/src/contexts/QuotationContext.tsx
FE-MyCarMaster/src/pages/Quotation.tsx

- #40 
- 변경하기 버튼을 통해 해당하는 페이지로 이동하게 하였습니다.
- 확정하기 / 고민해보기 버튼 기능 구현하였습니다.
- 총 금액 함수를 통해 총액 표시하였습니다.

[Feature] 견적서 완성 페이지 기능 구현

---

FE-MyCarMaster/src/App.tsx
FE-MyCarMaster/src/components/Footer/FoldScreen.tsx
FE-MyCarMaster/src/components/Footer/Footer.tsx
FE-MyCarMaster/src/components/Footer/SelectListWrapper.tsx
FE-MyCarMaster/src/components/Footer/view/ColorSelect.tsx
FE-MyCarMaster/src/components/Footer/view/DetailModelSelect.tsx
FE-MyCarMaster/src/components/Footer/view/OptionSelect.tsx
FE-MyCarMaster/src/components/Footer/view/TrimSelect.tsx
FE-MyCarMaster/src/components/Header/Header.tsx
FE-MyCarMaster/src/components/Main/MainView.tsx
FE-MyCarMaster/src/components/Main/view/DetailModelView/BodyTypeView.tsx
FE-MyCarMaster/src/components/Main/view/DetailModelView/WheelDriveView.tsx
FE-MyCarMaster/src/components/Main/view/OptionContent.tsx
FE-MyCarMaster/src/components/Main/view/TrimContent.tsx
FE-MyCarMaster/src/components/common/CategoryList/CategoryItem.tsx
FE-MyCarMaster/src/components/common/NavigationList/EstimatedPrice.tsx
FE-MyCarMaster/src/components/common/NavigationList/NavigationItem.tsx
FE-MyCarMaster/src/components/common/OptionBox/OptionBoxButtonContainer.tsx
FE-MyCarMaster/src/components/common/OptionBox/style.ts
FE-MyCarMaster/src/components/common/QuotationList/QuotationOptionList.tsx
FE-MyCarMaster/src/components/common/SearchTrimBox/SearchTrimBox.tsx
FE-MyCarMaster/src/components/common/SearchTrimBox/style.ts
FE-MyCarMaster/src/pages/Estimation.tsx
FE-MyCarMaster/src/styles/Theme.ts

- #198  
- 전체 레이아웃 재구성
- Filler 삭제 및 Footer에 적용
- 컬러박스에도 적용이 필요함

[Refactor] 컴포넌트 Style 재정리

---

FE-MyCarMaster/src/App.tsx
FE-MyCarMaster/src/components/Footer/FoldScreen.tsx
FE-MyCarMaster/src/components/Footer/Footer.tsx
FE-MyCarMaster/src/components/Header/Header.tsx
FE-MyCarMaster/src/components/common/OptionBox/style.ts
FE-MyCarMaster/src/pages/Home.tsx

- #6 
- 모델 선택 레이아웃으로 이동할 수 있다.
- 모델추가되면 넣어도 될 듯?
https://github.com/softeerbootcamp-2nd/H5-MyCarMaster/assets/82306066/ff19a389-0e1b-4fa8-b65d-0bb6929e810b

[Feature] 홈 화면 레이아웃 구성

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/agency/entity/AgencyEntity.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/entity/RepresentativeOptionEntity.java

- #239 
- agency entity에 gu 컬럼 추가

[Feature] agency entity에 gu 컬럼 및 representative option entity 추가

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/dto/response/CreateEstimateResponse.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/usecase/CreateEstimateUseCase.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/estimate/Estimate.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/estimate/adaptor/EstimateJpaAdaptor.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/estimate/entity/EstimateEntity.java

- uuid와 별도로 pk 생성
- uuid pk로 설정할 시 random값으로 insert 발생. 이러면 sort 계속 발생

[Setting] uuid와 별도로 pk 생성

---

.github/workflows/be-release-cd.yml
BE-MyCarMaster/Dockerfile
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/consult/controller/ConsultController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/consult/usecase/ApplyConsultingUseCase.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/controller/EstimateController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/usecase/port/EstimatePort.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/config/CorsConfig.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/estimate/adaptor/EstimateJpaAdaptor.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/estimate/repository/EstimateJpaRepository.java
BE-MyCarMaster/src/main/resources/application-domain.yml
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/consult/ConsultControllerTest.java

- uuid 관련 로직 수정
- url 복수형으로 변겨
- CORS 추가

[Fix] 테이블 변경에 따른 구매 상담 신청 로직 수정

---

.github/workflows/be-release-cd.yml
BE-MyCarMaster/Dockerfile
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/consult/controller/ConsultController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/consult/usecase/ApplyConsultingUseCase.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/controller/EstimateController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/usecase/port/EstimatePort.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/config/CorsConfig.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/estimate/adaptor/EstimateJpaAdaptor.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/estimate/repository/EstimateJpaRepository.java
BE-MyCarMaster/src/main/resources/application-domain.yml
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/consult/ConsultControllerTest.java

[Release] CORS 추가 설정

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/config/CorsConfig.java

- allowMethods에 OPTIONS 메서드 추가
- 해당 설정으로 문제 해결되지 않을시 모든 origin 허용 예정

[Setting] allowMethods에 OPTIONS 메서드 추가

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/config/CorsConfig.java

- 모든 origin 허용
- 이번 작업도 안된다면 api 서버 이외에서 문제 발생 여부 확인해야함

[Setting] CORS 모든 origin 허용 

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/config/CorsConfig.java

[Release] 모든 origin 허용

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/controller/CarMasterController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/dto/request/FilterEnum.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/dto/request/GetCarMasterRequest.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/dto/response/CarMasterDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/dto/response/GetCarMasterResponse.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/usecase/GetCarMasterUseCase.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/annotation/valid/EnumValidator.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/annotation/valid/ValidEnum.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/car_master/controller/CarMasterControllerTest.java

[Feature] 카마스터 목록 조회 Controller 구현

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/controller/OptionController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/dto/request/GetRepresentativeOptionsRequest.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/dto/response/AppliedOptionDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/dto/response/FilterDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/dto/response/GetRepresentativeOptionsResponse.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/dto/response/RepresentativeOptionDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/usecase/GetRepresentativeOptionsUseCase.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/usecase/port/OptionPort.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/trim/usecase/port/TrimPort.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/adaptor/OptionJpaAdaptor.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/entity/OptionEntity.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/entity/RepresentativeOptionEntity.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/repository/RepresentativeOptionJpaRepository.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/repository/TrimAdditionalOptionJpaRepository.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/repository/TrimDefaultOptionJpaRepository.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/trim/adaptor/TrimJpaAdaptor.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/trim/repository/TrimJpaRepository.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/option/controller/OptionControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/option/usecase/GetRepresentativeOptionsUseCaseTest.java

- #216 
- option entity의 img_url nullable로 설정 및 description length 1000으로 설정
- 모델별 대표옵션 목록 조회 관련 Dto, entity 구현
- 모델별 대표옵션 목록 조회 기능 구현

[Feature] 모델별 대표옵션 목록 조회 구현

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/controller/CarMasterController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/dto/request/FilterEnum.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/dto/request/GetCarMasterRequest.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/dto/response/AgencyDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/dto/response/CarMasterAgencyDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/dto/response/CarMasterDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/dto/response/GetCarMasterResponse.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/usecase/GetCarMasterUseCase.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/usecase/port/AgencyPort.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/consult/usecase/port/CarMasterPort.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/agency/Agency.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/car_master/CarMaster.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/annotation/valid/EnumValidator.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/exception/GlobalExceptionHandler.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/agency/adaptor/AgencyJpaAdaptor.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/agency/entity/AgencyEntity.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/agency/repository/AgencyJpaRepository.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/car_master/adaptor/CarMasterJpaAdaptor.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/car_master/entity/CarMasterEntity.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/car_master/repository/CarMasterJpaRepository.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/car_master/controller/CarMasterControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/car_master/usecase/GetCarMasterUseCaseTest.java

- #238 
- 카마스터 목록 조회
- EnumValidator 추가
- 현재는  동적 쿼리 사용할 필요없이 분기문으로 처리하는게 더 적합하다고 판단

[Feature] 카마스터 목록 조회 구현

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/agency/controller/AgencyController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/agency/dto/request/GetAgenciesRequest.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/agency/dto/response/AgencyDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/agency/dto/response/GetAgenciesResponse.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/agency/usecase/GetAgenciesUseCase.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/agency/AgencyControllerTest.java

[Feature] 대리점 목록 조회 Controller 구현

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/dto/response/AppliedOptionDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/dto/response/DefaultOptionDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/dto/response/OptionDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/option/Category.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/option/Option.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/option/controller/OptionControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/option/usecase/GetDefaultOptionsUseCaseTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/option/usecase/GetOptionsUseCaseTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/option/usecase/GetRepresentativeOptionsUseCaseTest.java

- #24 
- 옵션 목록 조회시 카테고리명 한글로 보내도록 수정

[Chore] 옵션 목록 조회시 카테고리 한글로 수정

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/agency/controller/AgencyController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/agency/dto/response/AgencyInGuDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/agency/dto/response/GetAgenciesResponse.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/agency/usecase/GetAgenciesUseCase.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/controller/CarMasterController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/usecase/port/AgencyPort.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/agency/adaptor/AgencyJpaAdaptor.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/agency/entity/AgencyEntity.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/agency/repository/AgencyJpaRepository.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/agency/AgencyControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/agency/usecase/GetAgenciesUseCaseTest.java

- #239 
- 지역구를 기준으로 대리점 목록 조회 기능 구현

[Feature] 지역구로 대리점 목록 조회 기능 구현

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/agency/controller/AgencyController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/agency/dto/response/CarMasterInAgencyDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/agency/dto/response/GetCarMastersInAgencyResponse.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/agency/usecase/GetCarMastersInAgencyUseCase.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/consult/usecase/port/CarMasterPort.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/car_master/adaptor/CarMasterJpaAdaptor.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/car_master/entity/CarMasterEntity.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/car_master/repository/CarMasterJpaRepository.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/agency/AgencyControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/agency/usecase/GetCarMastersInAgencyUseCaseTest.java

- #238 
- 대리점에 속한 카마스터 조회 API 구현
- 거의 공통 되는 DTO가 계속 발생. 어떻게 처리할지 논의가 필요하다.
- agency 패키지에 존재하는데 카마스터 조회하는 중... 이 부분도 논의가 필요하다.

[Feature] 대리점에 속한 카마스터 조회 API 구현

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/dto/response/AppliedOptionDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/dto/response/DefaultOptionDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/dto/response/OptionDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/trim/controller/TrimController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/trim/dto/response/GetTrimDefaultOptionsResponse.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/trim/dto/response/TrimDefaultOptionDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/trim/usecase/GetTrimDefaultOptionsUseCase.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/option/Option.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/option/usecase/GetDefaultOptionsUseCaseTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/option/usecase/GetOptionsUseCaseTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/option/usecase/GetRepresentativeOptionsUseCaseTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/trim/controller/TrimControllerTest.java

- #204 
- 트림의 기본 옵션 목록 조회 기능을 위한 dto 및 controller 구현
- usecase 추가
- TC 작성

[Feature] 트림 기본 옵션 목록 조회 Controller 구현

---

FE-MyCarMaster/src/components/Footer/screen_view/MyTrimSearchScreen.tsx
FE-MyCarMaster/src/components/Footer/view/TrimSelect.tsx
FE-MyCarMaster/src/components/common/BasicOptionModal/BasicOptionModal.tsx
FE-MyCarMaster/src/components/common/CheckBox/OptionCheckBox.tsx
FE-MyCarMaster/src/components/common/OptionBox/OptionBox.tsx
FE-MyCarMaster/src/components/common/OptionDescriptionModal/OptionDescriptionModal.tsx
FE-MyCarMaster/src/components/common/OptionList/style.ts
FE-MyCarMaster/src/contexts/QuotationContext.tsx
FE-MyCarMaster/src/types/options.types.ts
FE-MyCarMaster/src/types/quotation.types.ts

- #190 
- 트림 기본 옵션을 보여주는 모달 생성
- 내게 맞는 트림 찾기 및 옵션 페이지에서 기본 옵션을 보여줄 때 사용하는 모달 생성
- 내게 맞는 트림 찾기 내 모달 시 position: fixed로 하였는데 width, height 문제를 어떻게 해결할 것인가..
- 내게 맞는 트림 찾기 내 모달에서 선택하기를 누르면 트림 필터링이 적용되는데, 체크 박스에 체크를 해주어야함. 그것은 OptionBox에서 일어나는데 어떻게 전달해줄까?

[Feature] 기본 옵션 모달 및 옵션 상세 보기 모달 구현

---

FE-MyCarMaster/src/components/Footer/view/OptionSelect.tsx
FE-MyCarMaster/src/components/Header/Header.tsx
FE-MyCarMaster/src/contexts/OptionContext.tsx
FE-MyCarMaster/src/pages/Quotation.tsx
FE-MyCarMaster/src/types/options.types.ts

- #247 
- #192
- 내게 맞는 트림 찾기에서 적용된 옵션이 추가옵션 선택뷰에서 적용이 되도록 조정
- 견적서 완성페이지에서 블루 스크린 적용 확인
- 로고 이미지 위치 조정

[Fix] 스타일 및 내게 맞는 트림 찾기 옵션 적용

---

FE-MyCarMaster/src/components/common/NavigationList/NavigationItem.tsx
FE-MyCarMaster/src/styles/GlobalStyle.ts

[Fix] 네비게이션 옵션 설정 및 폰트 경로 수정

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/agency/dto/response/CarMasterInAgencyDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/car_master/entity/CarMasterEntity.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/agency/usecase/GetCarMastersInAgencyUseCaseTest.java

- #238 
- 카마스터 정보에 소속 대리점 추가
- 이곳에도 중복 DTO 발생.

[Feature] 카마스터 정보에 소속 대리점 추가

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/controller/EstimateController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/dto/response/GetEstimateResponse.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/dto/response/SimpleBodyTypeDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/dto/response/SimpleEngineDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/dto/response/SimpleExteriorColorDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/dto/response/SimpleInteriorColorDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/dto/response/SimpleOptionDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/dto/response/SimpleTrimDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/dto/response/SimpleWheelDriveDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/usecase/GetEstimateUseCase.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/usecase/port/EstimatePort.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/estimate/Estimate.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/color_exterior/entity/ExteriorColorEntity.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/color_exterior/entity/TrimExteriorColorEntity.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/color_interior/entity/InteriorColorEntity.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/color_interior/entity/TrimInteriorColorEntity.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/estimate/adaptor/EstimateJpaAdaptor.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/estimate/entity/EstimateAdditionalOptionEntity.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/estimate/entity/EstimateConsiderOptionEntity.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/estimate/entity/EstimateEntity.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/estimate/repository/EstimateJpaRepository.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/entity/OptionEntity.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/trim/entity/TrimEntity.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/estimate/controller/EstimateControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/estimate/usecase/GetEstimateUseCaseTest.java

- #285 
- 견적서 조회 리스폰스에 필요한 DTO 생성
- Usecase 구현
- 지금 fetch join으로 필요없는 데이터까지 다 가져오고 있다... 추후 수정해야할듯

[Feature] 견적서 조회 기능 구현

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/config/RedisConfig.java
BE-MyCarMaster/src/main/resources/application-domain.yml

- 환경변수를 제대로 가져오지 못하는 문제 발생. spring. 을 앞에 붙여서 해결

[Fix] 환경변수 설정 수정

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/config/RedisConfig.java
BE-MyCarMaster/src/main/resources/application-domain.yml

- 환경변수를 제대로 가져오지 못하는 문제 발생. spring. 을 앞에 붙여서 해결

[Release] 환경변수 설정 수정

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/model/controller/ModelController.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/model/controller/ModelControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/model/usecase/GetModelsUseCaseTest.java

[Refactor] model 관련 response 변수명 컨벤션에 맞게 수정

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/usecase/CreateEstimateUseCase.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/usecase/GetDefaultOptionsUseCase.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/usecase/port/OptionPort.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/trim/controller/TrimController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/trim/usecase/GetTrimDefaultOptionsUseCase.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/trim/usecase/GetTrimsUseCase.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/trim/usecase/port/TrimPort.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/adaptor/OptionJpaAdaptor.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/trim/adaptor/TrimJpaAdaptor.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/option/usecase/GetDefaultOptionsUseCaseTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/trim/controller/TrimControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/trim/usecase/GetTrimDefaultOptionsUseCaseTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/trim/usecase/GetTrimsUseCaseTest.java

- #291 
- 트림 목록 조회 리팩토링
- 트림 기본 옵션 조회 리팩토링

[Refactor] 트림 목록 조회 리팩토링

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/usecase/CreateEstimateUseCase.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/model/controller/ModelController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/model/usecase/get_models/GetModelsJpaAdaptor.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/model/usecase/get_models/GetModelsPort.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/model/usecase/get_models/GetModelsUseCase.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/model/controller/ModelControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/model/usecase/GetModelsUseCaseTest.java

- #291 
- port, adaptor usecase 단위로 패키지 구조 수정 및 rename

[Refactor] model port, adaptor 패키지 구조 변경 및 rename

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/engine/controller/EngineController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/engine/usecase/get_engines/GetEnginesJpaAdaptor.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/engine/usecase/get_engines/GetEnginesPort.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/engine/usecase/get_engines/GetEnginesUseCase.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/engine/controller/EngineControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/engine/usecase/GetEnginesUseCaseTest.java

[Refactor] engine 패키지 구조 변경 및 usecase별 port, adaptor 추가

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/agency/controller/AgencyController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/agency/usecase/get_agencies/GetAgenciesAdaptor.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/agency/usecase/get_agencies/GetAgenciesPort.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/agency/usecase/get_agencies/GetAgenciesUseCase.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/agency/AgencyControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/agency/usecase/GetAgenciesUseCaseTest.java

[Refactor] agency 패키지 구조 변경 및 usecase 단위 port, adapter 추가

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/engine/controller/EngineController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/controller/DefaultOptionController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/controller/OptionController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/controller/RepresentativeOptionController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/usecase/get_default_options/GetDefaultOptionsAdaptor.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/usecase/get_default_options/GetDefaultOptionsPort.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/usecase/get_default_options/GetDefaultOptionsUseCase.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/usecase/get_options/GetOptionsJpaAdaptor.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/usecase/get_options/GetOptionsPort.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/usecase/get_options/GetOptionsUseCase.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/usecase/get_representative_options/GetRepresentativeOptionsAdaptor.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/usecase/get_representative_options/GetRepresentativeOptionsPort.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/usecase/get_representative_options/GetRepresentativeOptionsUseCase.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/usecase/get_trim_default_options/GetTrimDefaultOptionsAdaptor.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/usecase/get_trim_default_options/GetTrimDefaultOptionsPort.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/usecase/get_trim_default_options/GetTrimDefaultOptionsUseCase.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/usecase/get_unselectable_options_by_engine/GetUnselectableOptionsByEngineAdaptor.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/usecase/get_unselectable_options_by_engine/GetUnselectableOptionsByEnginePort.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/usecase/get_unselectable_options_by_engine/GetUnselectableOptionsByEngineUseCase.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/trim/controller/TrimController.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/engine/controller/EngineControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/engine/usecase/GetUnselectableOptionsByEngineUseCaseTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/option/controller/DefaultOptionControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/option/controller/OptionControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/option/controller/RepresentativeOptionControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/option/usecase/GetDefaultOptionsUseCaseTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/option/usecase/GetOptionsUseCaseTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/option/usecase/GetRepresentativeOptionsUseCaseTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/trim/controller/TrimControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/trim/usecase/GetTrimDefaultOptionsUseCaseTest.java

- #291 
- 옵션 조회 리팩토링
- 엔진별 선택 불가능한 옵션 조회 리팩토링
- 기본 옵션 조회 리팩토링
- 세부사항별 옵션 조회 리팩토링
- 대표 옵션 조회 리팩토링
- 대표 옵션 조회시 stream에서 데이터 가져오는중. 해당 부분 확인 필요

[Refactor] option 패키지 구조 변경 및 usecase 단위 port, adapter 추가

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/agency/controller/AgencyController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/controller/CarMasterController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/usecase/GetCarMastersInAgencyUseCase.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/usecase/get_car_masters/GetCarMasterUseCase.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/usecase/get_car_masters/GetCarMastersAdaptor.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/usecase/get_car_masters/GetCarMastersPort.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/usecase/get_car_masters_in_agency/GetCarMastersInAgencyAdaptor.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/usecase/get_car_masters_in_agency/GetCarMastersInAgencyPort.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/usecase/get_car_masters_in_agency/GetCarMastersInAgencyUseCase.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/agency/AgencyControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/agency/usecase/GetCarMastersInAgencyUseCaseTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/car_master/controller/CarMasterControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/car_master/usecase/GetCarMasterUseCaseTest.java

[Refactor] car-master 패키지 구조 변경 및 usecase 단위 port, adapter 추가

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/color_interior/controller/InteriorColorController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/color_interior/usecase/get_interior_colors/GetInteriorColorsJpaAdaptor.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/color_interior/usecase/get_interior_colors/GetInteriorColorsPort.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/color_interior/usecase/get_interior_colors/GetInteriorColorsUseCase.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/color_interior/controller/InteriorColorControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/color_interior/usecase/GetInteriorColorsUseCaseTest.java

[Refactor] interior color 패키지 구조 변경 및 usecase 단위 port, adapter 추가

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/color_exterior/controller/ExteriorColorController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/color_exterior/usecase/get_exterior_colors/GetExteriorColorsJpaAdaptor.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/color_exterior/usecase/get_exterior_colors/GetExteriorColorsPort.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/color_exterior/usecase/get_exterior_colors/GetExteriorColorsUseCase.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/color_exterior/controller/ExteriorColorControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/color_exterior/usecase/GetExteriorColorsUseCaseTest.java

[Refactor] exterior color 패키지 구조 변경 및 usecase 단위 port, adapter 추가

---

FE-MyCarMaster/src/components/Footer/screen_view/DefaultOptionScreen.tsx
FE-MyCarMaster/src/components/Footer/screen_view/MyTrimSearchScreen.tsx
FE-MyCarMaster/src/components/Footer/view/ColorView/ExteriorColorSelectView.tsx
FE-MyCarMaster/src/components/Footer/view/ColorView/InteriorColorSelectView.tsx
FE-MyCarMaster/src/components/Footer/view/DetailModelView/BodyTypeSelectView.tsx
FE-MyCarMaster/src/components/Footer/view/DetailModelView/EngineSelectView.tsx
FE-MyCarMaster/src/components/Footer/view/DetailModelView/WheelDriveSelectView.tsx
FE-MyCarMaster/src/components/Footer/view/TrimSelect.tsx
FE-MyCarMaster/src/components/common/Modals/ModalContents/ConfirmModal.tsx
FE-MyCarMaster/src/components/common/Modals/Modals.tsx
FE-MyCarMaster/src/components/common/NavigationList/NavigationItem.tsx
FE-MyCarMaster/src/components/common/NavigationList/NavigationList.tsx
FE-MyCarMaster/src/components/common/OptionDescriptionModal/OptionDescriptionModal.tsx
FE-MyCarMaster/src/components/common/OptionList/GridOptionList.tsx
FE-MyCarMaster/src/components/common/QuotationList/QuotationItem.tsx
FE-MyCarMaster/src/components/common/QuotationList/QuotationList.tsx
FE-MyCarMaster/src/components/common/QuotationList/QuotationOptionItem.tsx
FE-MyCarMaster/src/components/common/QuotationList/QuotationOptionList.tsx
FE-MyCarMaster/src/constants/Modal.constants.ts
FE-MyCarMaster/src/contexts/QuotationContext.tsx
FE-MyCarMaster/src/pages/Quotation.tsx
FE-MyCarMaster/src/types/options.types.ts
FE-MyCarMaster/src/types/quotation.types.ts
FE-MyCarMaster/src/utils/fetch.ts

- #190 
- #327 
- 재사용 가능한 모달 컴포넌트를 이용하여 옵션 페이지 내 모달 구현했습니다.
- 견적서 완성 페이지 내에서 확정하기 버튼을 누르면 수정이 불가능하도록 구현했습니다.

[Feature] 옵션 내 모달 연결 및 확정 기능 구현

---

FE-MyCarMaster/src/components/Footer/screen_view/MyTrimSearchScreen.tsx
FE-MyCarMaster/src/components/common/CheckBox/OptionCheckBox.tsx
FE-MyCarMaster/src/components/common/OptionDescriptionModal/OptionDescriptionModal.tsx

[Feature] 내게 맞는 트림 찾기 구성 및 데이터 연동

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/consult/controller/ConsultController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/consult/usecase/apply_consulting/ApplyConsultingAdaptor.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/consult/usecase/apply_consulting/ApplyConsultingPort.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/consult/usecase/apply_consulting/ApplyConsultingUseCase.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/consult/ConsultControllerTest.java

[Refactor] consulting 패키지 구조 변경 및 usecase 단위 port, adapter 추가

---

FE-MyCarMaster/src/components/Footer/screen_view/DefaultOptionScreen.tsx
FE-MyCarMaster/src/components/Footer/screen_view/MyTrimSearchScreen.tsx
FE-MyCarMaster/src/components/Footer/view/OptionSelect.tsx
FE-MyCarMaster/src/components/common/NavigationList/NavigationList.tsx
FE-MyCarMaster/src/components/common/OptionList/GridOptionList.tsx
FE-MyCarMaster/src/hooks/useFadeAnimation.ts

- #328 
- 추가 옵션 뷰에서 기본 옵션 보기 API 연결 및 확인
- 기본 옵션 보기내 카테고리별 페이지네이션 추가
- 이미지 지금 제대로 안보임 -> 말해야할듯?

[Feature] 각 트림의 기본 옵션 보기

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/color_exterior/ExteriorColor.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/domain/body_type/BodyTypeTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/domain/color_exterior/ExteriorColorTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/domain/color_interior/InteriorColorTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/domain/engine/EngineTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/domain/model/ModelTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/domain/trim/TrimTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/domain/wheel_dirve/WheelDriveTest.java

[Test] Domain TC 작성

---

BE-MyCarMaster/build.gradle
BE-MyCarMaster/src/main/resources/application-api.yml

[Setting] Monitoring 설정

---

FE-MyCarMaster/src/components/Footer/FoldScreen.tsx
FE-MyCarMaster/src/components/Footer/screen_view/MyTrimSearchScreen.tsx
FE-MyCarMaster/src/components/common/NavigationList/NavigationList.tsx
FE-MyCarMaster/src/components/common/SnackBar/SnackBar.tsx
FE-MyCarMaster/src/components/common/SnackBar/style.ts
FE-MyCarMaster/src/hooks/keyframe.css
FE-MyCarMaster/src/hooks/useFadeAnimation.ts

- #328 
- createPortal 스낵바 퍼블리싱
- 스낵바 적용 및 핸들러 구현
- 애니메이션 효과 적용 및 커스텀 훅 사용
- [커스텀 애니메이션 훅](https://codesandbox.io/s/simple-component-fade-on-mount-3gjkn?from-embed=&initialpath=/example2&file=/src/Example2.js:462-469)
- [createPortal 리액트 문서](https://react.dev/reference/react-dom/createPortal#createportal)

[Feature] 모달 및 옵션에 사용되는 재사용 컴포넌트 생성

---

BE-MyCarMaster/build.gradle
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/agency/controller/AgencyController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/body_type/controller/BodyTypeController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/car_master/controller/CarMasterController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/color_exterior/controller/ExteriorColorController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/color_interior/controller/InteriorColorController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/engine/controller/EngineController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/option/controller/DefaultOptionController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/option/controller/OptionController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/option/controller/RepresentativeOptionController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/trim/controller/TrimController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/wheeldrive/controller/WheelDriveController.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/aspect/BindingAdvice.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/exception/BindingAdvice.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/application/agency/controller/AgencyControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/application/body_type/controller/BodyTypeControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/application/car_master/controller/CarMasterControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/application/color_exterior/controller/ExteriorColorControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/application/color_interior/controller/InteriorColorControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/application/engine/controller/EngineControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/application/option/controller/DefaultOptionControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/application/option/controller/OptionControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/application/option/controller/RepresentativeOptionControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/application/trim/controller/TrimControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/application/wheeldrive/controller/WheelDriveControllerTest.java

- BindingAdvice 추가
- 위치 저기가 맞나..?
- 이름도 저게 맞는지 모르겠다.
- 테스트 계속 실패해서 적용이 안되고 있는줄 알고 한참동안 삽질했는데, 테스트코드에 어노테이션을 추가해야지 적용되는거였다...🫠

[Feature] BindingRequest 관련 예외처리 로직 AOP로 분리

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/option/Category.java

- #24 
- 프론트와 네이밍이 달라 필터링 되지 않는 문제가 생겨 수정

[Chore] category 중 '지능형 안전기술' rename

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/estimate/dto/response/EstimateOptionDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/estimate/entity/EstimateEntity.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/estimate/entity/EstimateSelectOptionEntity.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/entity/OptionEntity.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/application/estimate/controller/EstimateControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/application/estimate/usecase/GetEstimateUseCaseTest.java

- #285 
- estimate_additional_options => estimate_select_options 로 rename
- 견적서 조회 응답에 option category 추가
- TC 수정

[Feature] 견적서 조회 응답에 option category 추가

---

BE-MyCarMaster/src/main/resources/application-api.yml

- package 이름을 api -> application으로 변경함에 따라 yml의 scan package 재설정

[Fix] swagger 오류 해결

---

.github/workflows/be-release-cd.yml

[Fix] 메일 관련 환경 변수명 수정

---

.github/workflows/be-release-cd.yml
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/car_master/usecase/get_car_masters/GetCarMasterUseCase.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/car_master/usecase/get_car_masters/GetCarMastersAdaptor.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/car_master/usecase/get_car_masters/GetCarMastersPort.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/estimate/dto/response/CreateEstimateResponse.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/agency/entity/AgencyEntity.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/car_master/repository/CarMasterJpaRepository.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/application/car_master/usecase/GetCarMasterUseCaseTest.java

[Release] 환경 변수 수정 및 조회 로직 수정

---

FE-MyCarMaster/src/App.tsx
FE-MyCarMaster/src/components/common/QuotationList/QuotationOptionItem.tsx
FE-MyCarMaster/src/components/common/QuotationList/QuotationOptionList.tsx
FE-MyCarMaster/src/pages/ConsultComplete.tsx
FE-MyCarMaster/src/pages/WrittenQuotation.tsx
FE-MyCarMaster/src/pages/index.ts

- #361 
- 이메일로 발송된 url을 통한 견적서 조회 페이지 구현했습니다.
- 구매 상담 신청 완료 페이지 구현했습니다.

[FE-Feature] 이메일을 통한 견적서 조회 페이지 구현

---

BE-MyCarMaster/scripts/appspec.yml
BE-MyCarMaster/scripts/promtail-config.yml
BE-MyCarMaster/scripts/pull-and-run-container.sh

[Setting] 로그 관리를 위한 설정

---

BE-MyCarMaster/scripts/appspec.yml
BE-MyCarMaster/scripts/promtail-config.yml
BE-MyCarMaster/scripts/pull-and-run-container.sh

[Release] 로그 관리를 위한 설정

---

BE-MyCarMaster/scripts/appspec.yml

- scripts/promtail-config.yml -> promtail-config.yml 로 수정

[Setting] codedeploy 파일 원본 경로 수정

---

BE-MyCarMaster/scripts/appspec.yml

- promtail-config.yml 원본 경로 수정

[Fix] promtail-config.yml 원본 경로 수정 (#366)

---

BE-MyCarMaster/scripts/pull-and-run-container.sh

- 로그 저장을 위한 volume mounting 설정

[Setting] volume mounting 설정

---

FE-MyCarMaster/src/App.tsx
FE-MyCarMaster/src/components/Footer/view/OptionSelect.tsx
FE-MyCarMaster/src/components/common/FormModal/FormModal.tsx
FE-MyCarMaster/src/components/common/Modals/ModalContents/ConfirmModal.tsx
FE-MyCarMaster/src/components/common/SeoulMap/SeoulMap.tsx
FE-MyCarMaster/src/pages/WrittenQuotation.tsx

[FE-Refactor] 견적서 및 지도 리팩토링(1)

---

FE-MyCarMaster/src/App.tsx
FE-MyCarMaster/src/components/Footer/view/OptionSelect.tsx
FE-MyCarMaster/src/components/common/DistrictCarMasterList/DistrictCarMasterList.tsx
FE-MyCarMaster/src/components/common/FormModal/FormModal.tsx
FE-MyCarMaster/src/components/common/MapModal/MapModal.tsx
FE-MyCarMaster/src/components/common/Modals/ModalContents/ConfirmModal.tsx
FE-MyCarMaster/src/components/common/SeoulMap/SeoulMap.tsx
FE-MyCarMaster/src/pages/WrittenQuotation.tsx

[Fix] 빌드 오류 수정

---

.github/workflows/be-release-cd.yml
BE-MyCarMaster/Dockerfile
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/HealthController.java
BE-MyCarMaster/src/main/resources/application-domain.yml

- 로그 테스트를 위한 API 추가
- batch size 환경 변수 설정

[Release] 로그 관련 설정

---

BE-MyCarMaster/scripts/appspec.yml
BE-MyCarMaster/scripts/create-directory.sh
BE-MyCarMaster/scripts/remove-directory.sh

- promtail 설정을 위한 appspec 관련 스크립트 수정

[Setting] codedeploy 내용 수정

---

.github/workflows/be-release-cd.yml
BE-MyCarMaster/Dockerfile
BE-MyCarMaster/scripts/appspec.yml
BE-MyCarMaster/scripts/create-directory.sh
BE-MyCarMaster/scripts/remove-directory.sh
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/HealthController.java
BE-MyCarMaster/src/main/resources/application-domain.yml

[Release] Codedeploy script 수정

---

BE-MyCarMaster/scripts/remove-container.sh
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/agency/repository/AgencyJpaRepository.java

[Release] 카마스터 조회 기준 변경

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/model/dto/response/ModelDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/model/usecase/get_models/GetModelsJpaAdaptor.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/model/Model.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/model/Type.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/config/BaseTime.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/model/entity/ModelEntity.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/model/repository/ModelJpaRepository.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/application/estimate/usecase/create_estimate/CreateEstimateUseCaseTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/application/model/controller/ModelControllerTest.java
BE-MyCarMaster/src/test/java/softeer/be_my_car_master/application/model/usecase/GetModelsUseCaseTest.java

[Release] 모델  조회시 Response 추가

---

FE-MyCarMaster/src/components/Main/view/ColorView/ExteriorColorView.tsx
FE-MyCarMaster/src/components/common/CarRotation/SpriteCarRotation.tsx
FE-MyCarMaster/src/components/common/index.ts

- #194 
- 기존 성능과 Sprite 이미지를 비교하기위해 구현하였다.
- API에 따라 제공받을 수 있는 이미지 경로를 다르게 설정할 수 있는 option 추가

[FE-Feature] 차량 360도 회전

---

FE-MyCarMaster/src/App.tsx

[Fix] 배포 빌드 전 에러 수정

---

BE-MyCarMaster/build.gradle
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/agency/entity/AgencyEntity.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/agency/repository/AgencyJpaRepository.java
BE-MyCarMaster/src/main/resources/application-domain.yml

[Release] 카마스터 조회 쿼리 튜닝

---

BE-MyCarMaster/src/main/resources/application-domain.yml

- #373 
- prod 환경에 dialect 적용되지 않았었음. 해당 부분 설정 추가

[Fix] dialect 설정 추가

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/car_master/usecase/get_car_masters/GetCarMasterUseCase.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/config/CacheConfig.java

- #291
- Redis를 이용하여 카마스터 조회에 cache 적용.
- usecase 수준에 적용.

[Refactor] 카마스터 조회에 캐시 적용

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/car_master/usecase/get_car_masters/GetCarMasterUseCase.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/config/CacheConfig.java

[Release] 카마스터 조회에 캐시 적용

---

FE-MyCarMaster/src/components/common/OptionDescriptionModal/OptionDescriptionModal.tsx

- #402 
- 세부 설명 모달 portal로 변경하여 background overlay 부분 적용 해결하였습니다.

[FE-Fix] 세부 설명 모달 수정

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/car_master/usecase/get_car_masters/GetCarMasterUseCase.java

[Refactor] 카마스터 조회 API cache 적용 해제

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/car_master/usecase/get_car_masters/GetCarMasterUseCase.java

[Release] 카마스터 조회 API cache 적용 해제

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/consult/handler/MailSendHandler.java

[Remove] 이메일 전송 관련 @Async 비활성화

---

FE-MyCarMaster/src/assets/icons/UnderBar.svg
FE-MyCarMaster/src/components/Footer/screen_view/DefaultOptionScreen.tsx
FE-MyCarMaster/src/components/Home/ModelSelectView.tsx
FE-MyCarMaster/src/components/Home/style.ts
FE-MyCarMaster/src/components/Main/view/ColorView/ExteriorColorView.tsx
FE-MyCarMaster/src/components/common/BasicOptionModal/BasicOptionModal.tsx
FE-MyCarMaster/src/components/common/Button/TextButton.tsx
FE-MyCarMaster/src/components/common/CarMasterItem/style.ts
FE-MyCarMaster/src/components/common/CarRotation/CarRotation.tsx
FE-MyCarMaster/src/components/common/CarRotation/SpriteCarRotation.tsx
FE-MyCarMaster/src/components/common/DistrictCarMasterList/DistrictCarMasterList.tsx
FE-MyCarMaster/src/components/common/ErrorBoundary/style.ts
FE-MyCarMaster/src/components/common/FormModal/FormModal.tsx
FE-MyCarMaster/src/components/common/MapModal/style.ts
FE-MyCarMaster/src/components/common/Modals/ModalContents/AlertModal.tsx
FE-MyCarMaster/src/components/common/Modals/ModalContents/ChangeTrimModal.tsx
FE-MyCarMaster/src/components/common/Modals/ModalContents/ConfirmModal.tsx
FE-MyCarMaster/src/components/common/Modals/ModalContents/ExitModal.tsx
FE-MyCarMaster/src/components/common/OptionDescription/OptionDescription.tsx
FE-MyCarMaster/src/components/common/QuotationList/QuotationItem.tsx
FE-MyCarMaster/src/components/common/QuotationList/QuotationList.tsx
FE-MyCarMaster/src/components/common/QuotationList/QuotationOptionItem.tsx
FE-MyCarMaster/src/components/common/QuotationList/QuotationOptionList.tsx
FE-MyCarMaster/src/components/common/SnackBar/style.ts
FE-MyCarMaster/src/pages/ConsultComplete.tsx
FE-MyCarMaster/src/pages/Home.tsx
FE-MyCarMaster/src/pages/Quotation.tsx
FE-MyCarMaster/src/pages/WrittenQuotation.tsx
FE-MyCarMaster/src/styles/Theme.ts

- #198 
- Font Bold 제거 및 Medium으로 교체
- exteriorColorView에서 text 및 UnderBar 이미지 추가

[FE-Refactor] 컴포넌트 Style 재정리

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/consult/handler/MailSendHandler.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/config/SchedulingConfig.java

[Setting] @Async 설정

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/consult/handler/MailSendHandler.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/config/SchedulingConfig.java

[Release] @Async 설정

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/consult/handler/MailSendHandler.java

[Setting] 이메일 전송 관련 @Async 비활성화

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/consult/handler/MailSendHandler.java

[Release] 이메일 전송 관련 @Async 비활성화

---

iOS-MyCarMaster/MyCarMaster/MyCarMaster/Manager/EstimationManager.swift
iOS-MyCarMaster/MyCarMaster/MyCarMaster/Scene/Step/Trim/TrimReactor.swift
iOS-MyCarMaster/MyCarMaster/MyCarMaster/Scene/Step/Trim/TrimViewController.swift

- #298 
- 트림 Step 이후의 진행상황이 있을 때, 트림을 변경하면 경고창 띄우기
- 없을 시, 띄우지 않음
- 경고 확인시, 적용
https://github.com/softeerbootcamp-2nd/H5-MyCarMaster/assets/46219689/6e70215c-959c-4591-af37-555956537d4b
- 없음

[iOS-Feature] 트림 이후 Step을 진행한 뒤, 트림을 변경할 때 경고창

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/consult/handler/MailSendHandler.java

[Setting] 이메일 전송 관련 @Async 활성화

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/consult/handler/MailSendHandler.java

[Release] 이메일 전송 관련 @Async 활성화

---

FE-MyCarMaster/src/components/common/CarRotation/SpriteCarRotation.tsx
FE-MyCarMaster/src/hooks/useFetch.ts
FE-MyCarMaster/src/pages/WrittenQuotation.tsx
FE-MyCarMaster/src/styles/core.style.ts

- #405
- Cache Storage를 이용하여 네트워크 요청 수를 줄였습니다.
- 추가로 더 해볼 수 있는 최적화는 뭐가 있지? prefetch? preload?

[FE-Refactor] Cache Storage를 이용한 요청 수 감소

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/body_type/dto/response/BodyTypeDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/body_type/usecase/get_body_types/GetBodyTypesUseCase.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/car_master/usecase/get_car_masters/GetCarMasterUseCase.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/option/dto/response/OptionDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/option/dto/response/SubOptionDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/option/usecase/get_options/GetOptionsUseCase.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/trim/usecase/get_trims/GetTrimsUseCase.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/config/CacheConfig.java

- #373
- 비즈니스 로직에 캐시 적용
- batch size 적용

[Setting] cache 및 batch size 적용

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/body_type/dto/response/BodyTypeDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/body_type/usecase/get_body_types/GetBodyTypesUseCase.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/car_master/usecase/get_car_masters/GetCarMasterUseCase.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/option/dto/response/OptionDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/option/dto/response/SubOptionDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/option/usecase/get_options/GetOptionsUseCase.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/trim/usecase/get_trims/GetTrimsUseCase.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/config/CacheConfig.java

[Release] cache 및 batch size 적용

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/color_exterior/dto/response/ExteriorColorDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/color_interior/dto/response/InteriorColorDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/consult/dto/response/ClientResponseDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/consult/dto/response/ConsultingDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/engine/dto/response/EngineDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/engine/dto/response/UnselectableOptionDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/model/dto/response/ModelDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/option/dto/request/GetDefaultOptionsRequest.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/option/dto/request/GetOptionsRequest.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/option/dto/request/GetRepresentativeOptionsRequest.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/option/dto/response/AppliedOptionDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/option/dto/response/DefaultOptionDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/option/dto/response/FilterDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/option/dto/response/RepresentativeOptionDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/trim/dto/response/TrimDefaultOptionDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/trim/dto/response/TrimDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/wheeldrive/dto/response/WheelDriveDto.java

[Feature] DTO에 기본 생성자 추가

---

BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/color_exterior/dto/response/ExteriorColorDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/color_interior/dto/response/InteriorColorDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/consult/dto/response/ClientResponseDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/consult/dto/response/ConsultingDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/engine/dto/response/EngineDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/engine/dto/response/UnselectableOptionDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/model/dto/response/ModelDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/option/dto/request/GetDefaultOptionsRequest.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/option/dto/request/GetOptionsRequest.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/option/dto/request/GetRepresentativeOptionsRequest.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/option/dto/response/AppliedOptionDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/option/dto/response/DefaultOptionDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/option/dto/response/FilterDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/option/dto/response/RepresentativeOptionDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/trim/dto/response/TrimDefaultOptionDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/trim/dto/response/TrimDto.java
BE-MyCarMaster/src/main/java/softeer/be_my_car_master/application/wheeldrive/dto/response/WheelDriveDto.java

[Release] DTO에 기본 생성자 추가

---

iOS-MyCarMaster/MyCarMaster/MyCarMaster/Scene/Step/BodyType/BodyTypeReactor.swift
iOS-MyCarMaster/MyCarMaster/MyCarMaster/Scene/Step/BodyType/BodyTypeViewController.swift
iOS-MyCarMaster/MyCarMaster/MyCarMaster/Scene/Step/Engine/EngineReactor.swift
iOS-MyCarMaster/MyCarMaster/MyCarMaster/Scene/Step/Engine/EngineViewController.swift
iOS-MyCarMaster/MyCarMaster/MyCarMaster/Scene/Step/Interior/InteriorReactor.swift
iOS-MyCarMaster/MyCarMaster/MyCarMaster/Scene/Step/Interior/InteriorViewController.swift
iOS-MyCarMaster/MyCarMaster/MyCarMaster/Scene/Step/WheelDrive/WheelDriveReactor.swift
iOS-MyCarMaster/MyCarMaster/MyCarMaster/Scene/Step/WheelDrive/WheelDriveViewController.swift

- #299 
- #300 
- #301 
- #302 
- 이미지를 네트워크 레이어에서 다운받는것으로 변경
- 이미지 캐시 적용

[iOS-Feature] 이미지 네트워크 레이어 연결 및 캐시 적용
